forms/models.py
from forms import db

import enum


class UniversityDegreeEnum(enum.Enum):
    diploma = 'دیپلم'
    associate = 'کاردانی'
    bachelor = 'کارشناسی'
    senior = 'کارشناسی ارشد'
    phd = 'دکتری'


class Applicant(db.Model):
    __tablename__ = 'applicants'

    pk = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(30), nullable=False)
    last_name = db.Column(db.String(45), nullable=False)
    national_id = db.Column(db.String(10), unique=True, nullable=False)
    age = db.Column(db.Integer, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    mobile_phone = db.Column(db.String(11), unique=True, nullable=False)
    Address = db.Column(db.Text)
    university = db.Column(db.String(80), nullable=False)
    university_subject = db.Column(db.String(50), nullable=False)

    university_degree = db.Column(db.Enum(UniversityDegreeEnum),
                            default=UniversityDegreeEnum.diploma,
                            nullable=True
                        )

    work_reputations = db.Column(db.Text, nullable=True)


    def __repr__(self):
        return f'{self.first_name} {self.last_name}'



class ElectronicApplicant(Applicant):
    __tablename__ = 'ElectronicApplicants'

    altium_designer = db.Column(db.Boolean, nullable=True, default=False)
    arduino = db.Column(db.Boolean, nullable=True, default=False)
    code_vision = db.Column(db.Boolean, nullable=True, default=False)
    proteus = db.Column(db.Boolean, nullable=True, default=False)
    atmel_studio = db.Column(db.Boolean, nullable=True, default=False)
    microcontroller = db.Column(db.Boolean, nullable=True, default=False)
    power = db.Column(db.Boolean, nullable=True, default=False)
    others = db.Column(db.Text, nullable=True)
    resume = db.Column(db.LargeBinary, nullable=True)
    expected_salary = db.Column(db.String(7), nullable=True)

forms/__init__.py
import os

from flask import Flask, render_template
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy



ALLOWED_EXTENSIONS = ['jpg', 'png', 'jpeg', 'pdf', 'docx']

db = SQLAlchemy()
migrate = Migrate()


def create_app(test_config=None):
    # creating and configuring the app
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_mapping(
        SECRET_KEY = 'devel-fapsco',
        DATABASE=os.path.join(app.instance_path, 'forms.sqlite'),
    )
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['UPLOAD_FOLDER'] = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'static/uploads')
    app.config['ALLOWED_EXTENSIONS'] = ALLOWED_EXTENSIONS
    app.config['MAX_CONTENT_LENGTH'] = 2 * 1024 * 1024;

    db.init_app(app)
    migrate.init_app(app, db)

    if test_config is None:
        # load the instance config when not testing and if exists
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config
        app.config.from_mapping(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    @app.route('/about')
    def about():
        return render_template('about.html')


    from .views.electronics import bp


    app.register_blueprint(bp)
    app.add_url_rule('/', 'index')
    
    return app

forms/views/electronics.py
from werkzeug.utils import secure_filename

from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)

from forms.models import db, Applicant, ElectronicApplicant, UniversityDegreeEnum
from forms.electronic_forms import ApplicantsCreationForm, ElectricalApplicantCreationForm
from forms import ALLOWED_EXTENSIONS


from datetime import datetime


bp = Blueprint('electronics', __name__)

@bp.route('/')
def index():
    return render_template('electronics/index-el.html')


@bp.route('/form', methods=['GET', 'POST'])
def create_request():
    form = ElectricalApplicantCreationForm()

    if form.validate_on_submit():

        applicant = ElectronicApplicant()
        form.populate_obj(applicant) 

        if form.degree.data == 'diploma':
            applicant.university_degree = UniversityDegreeEnum.diploma
        elif form.degree.data == 'associate':
            applicant.university_degree = UniversityDegreeEnum.associate
        elif form.degree.data == 'bahcelor':
            applicant.university_degree = UniversityDegreeEnum.bachelor
        elif form.degree.data == 'senior':
            applicant.university_degree = UniversityDegreeEnum.senior
        elif form.degree.data == 'phd':
            applicant.university_degree = UniversityDegreeEnum.phd
        
        db.session.add(applicant)
        db.session.commit()

        flash('درخواست شما با موفقیت ارسال شد', 'success')
        return redirect(url_for('electronics.upload_resume', id=applicant.pk))
    
    else:
        flash('لطفا ایرادات زیر را قبل از ارسال دوباره فرم برطرف کنید', 'danger')
        return render_template('electronics/employment-form.html', form=form)


def allowed_file(filename):    
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@bp.route('/resume/<id>', methods=['GET', 'POST'])
def upload_resume(id):
    if request.method == 'POST':
        if not request.files:
            flash('شما فایلی آپلود نکردید')
            return redirect(request.url)
        
        file = request.files['file']
        if file.filename == '':
            flash('فایل انتخاب نشده است')
            return redirect(request.url)
        
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            user = ElectronicApplicant.query.get(id)
            if user:
                user.resume = file
                user.save()
            
            flash('هیچ درخواستی با این شماره ملی وجود ندارد')
            return redirect(request.url)
        
        flash('فرمت فایل پذیرفته نیست')
        return redirect(request.url)

    return render_template('electronics/resume-upload.html')

forms/templates/about.html
{% extends 'base.html' %}

{% block title %}<title>About US</title>{% endblock %}

{% block content %}
<div class="card container mt-4 posts bg-dark">
    <div class="card-header">
    <h4 class="text-white text-align-right" align="right">
    درباره ما
    </h4>
    </div>
    <p class="text-white text-align-right" align="right">
    شرکت مهندسی فن آور پویا سپاهان با نام تجاری فاپسکو با بیش از 15سال سابقه تولید دستگاههای پزشکی ، پوست و زیبایی و نیز به عنوان تولید کننده انواع سیستم های وکیوم پزشکی و تجهیزات اندازه گیری الکترونیکی مشغول به فعالیت می باشد.
     اکنون فاپسکو پس از چندین سال تحقیق و کار مداوم و با استعانت از درگاه خداوند متعال و باهدف مرتفع نمودن نیاز مراکز درمانی به انواع سیستم ها وکیوم، مفتخر به طراحی وتولید دستگاه وکیوم تراپی هوشمندمی باشد همچنین با استفاده از توان علمی و مهندسی، موفق به تولید محصلات میکرودرم ابریژن، میکرو پیگمنتیشن ومیکرو نیدلینگ جهت استفاده در کلینیک های زیبایی با اخذ مجوز از وزارت بهداشت، درمان وآموزش پزشکی، غذاو دارو شده است
    </p>
    <p class="text-white text-align-right", align="right">
    برای اطلاعات بیشتر<a href="https://fanavarco.com/">  به وبسایت رسمی شرکت </a>مراجعه فرمائید.
    </p>
    <div class="card-body">
    </div>
    <div class="card-footer">
    </div>
</div>
{% endblock %}

forms/templates/base.html
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {% block title %}{% endblock %}

        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
            integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
    </head>
    <body>
        <nav class="navbar navbar-dark navbar-expand-lg navbar-light bg-dark">
        <ul class="navbar-nav">
            <li class="nav-item">
            <a href="{{ url_for('electronics.index') }}" class="navbar-brand ml-5">فاپسکو</a>
            </li>
            <li class="nav-item">
                <a href="{{ url_for('about') }}" class="nav-link">
                درباه ما
                </a>
            </li>
        </ul>
        </nav>
            {% block content %}
            {% endblock %}


        <script
            src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"
        ></script>
        <script></script>
    </body>
</html>

forms/templates/electronics/employment-form.html
{% extends 'base.html' %}

{% block title%}<title>job entry</title>{% endblock %}

{% block content %}
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class=" container alert alert-danger allign-text-right mt-2" align="right">
            {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

<div class="card container mt-4 posts bg-dark">
    <div class="card-header">
        <h4 class="text-white text-allign-right" align="right">
        فرم درخواست همکاری
        </h4>
    </div>
    <div class="card-body">
        <form method="post" action="" class="needs-validation" novalidate>
            {{ form.csrf_token }}
            <p class='text-white' align="right">
            اطلاعات هویتی
            </p>
            <hr/>
            <div class="form-inline">
                {{ form.first_name.label(class=" form-control-label text-white ml-sm-3", align="right") }} 
                {{ form.first_name(class="form-control mb-2 ml-sm-5 col-4") }}
                <div class="valid-feedback">مورد پذیرش</div>
                <div class="invalid-feedback">مورد پذیرش نیست</div>
                {{ form.last_name.label(class="form-control-label text-white ml-sm-3") }}
                {{ form.last_name(class="form-control mb-2 ml-sm-5 col-4") }}
                <div class="valid-feedback">مورد پذیرش</div>
                <div class="invalid-feedback">مورد پذیرش نیست</div>
            </div>
            <div class="form-inline mt-2">
                {{ form.national_id.label(class="form-control-label text-white ml-sm-3") }}
                {{ form.national_id(class="form-control mb-2 ml-sm-5 col-4") }}
                <div class="valid-feedback">مورد پذیرش</div>
                <div class="invalid-feedback">مورد پذیرش نیست</div>
                {{ form.age.label(class="form-control-label text-white ml-sm-3") }}
                {{ form.age(class="form-control mb-2 ml-sm-5 col-4") }}
                <div class="valid-feedback">مورد پذیرش</div>
                <div class="invalid-feedback">مورد پذیرش نیست</div>
            </div>
            <hr/>
            {% if form.first_name.errors %}
                <ul class="form-group mb-3" align="right">
                {% for error in form.first_name.errors %}
                    <li class="alert alert-danger form-control">
                    {{ error }}
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
            {% if form.last_name.errors %}
                <ul class="form-group" align="right">
                {% for error in form.last_name.errors %}
                    <li class="alert alert-danger form-control">
                    {{ error }}
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
            {% if form.national_id.errors %}
                <ul class="form-group" align="right">
                {% for error in form.national_id.errors %}
                    <li class="alert alert-danger form-control">
                    {{ error }}
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
            {% if form.age.errors %}
                <ul class="form-group" align="right">
                {% for error in form.age.errors %}
                    <li class="alert alert-danger form-control">
                    {{ error }}
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
            <hr/>
            <p class='text-white mt-4' align="right">
            اطلاعات تماس
            </p>
            <hr/>
            <div class="form-inline">
                {{ form.email.label(class="form-control-label text-white ml-sm-3") }}
                {{ form.email(class="form-control mb-2 ml-sm-5 col-4") }}
                <div class="valid-feedback">مورد پذیرش</div>
                <div class="invalid-feedback">مورد پذیرش نیست</div>
                {{ form.mobile_phone.label(class="form-control-label text-white ml-sm-3") }}
                {{ form.mobile_phone(class="form-control mb-2 ml-sm-5 col-4") }}
                <div class="valid-feedback">مورد پذیرش</div>
                <div class="invalid-feedback">مورد پذیرش نیست</div>
            </div>
            <div class="form-inline mt-2">
                {{ form.Address.label(class="form-control-label text-white ml-sm-3", align="right") }}
                {{ form.Address(class="form-control col-10 mb-2 ml-sm-5") }}
                <div class="valid-feedback">مورد پذیرش</div>
                <div class="invalid-feedback">مورد پذیرش نیست</div>
            </div>
            <hr/>
            {% if form.email.errors %}
                <ul class="form-group" align="right">
                {% for error in form.email.errors %}
                    <li class="alert alert-danger form-control">
                    {{ error }}
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
            {% if form.mobile_phone.errors %}
                <ul class="form-group" align="right">
                {% for error in form.mobile_phone.errors %}
                    <li class="alert alert-danger form-control">
                    {{ error }}
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
            {% if form.Address.errors %}
                <ul class="form-group" align="right">
                {% for error in form.Address.errors %}
                    <li class="alert alert-danger form-control">
                    {{ error }}
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
            <hr/>
            <p class='text-white mt-4' align="right">
            تحصیلات
            </p>
            <hr/>
            <div class="form-inline">
                {{ form.university.label(class="form-control-label text-white  ml-sm-3") }}
                {{ form.university(class="form-control mb-2 ml-sm-5 col-2") }}
                <div class="valid-feedback">مورد پذیرش</div>
                <div class="invalid-feedback">مورد پذیرش نیست</div>
                {{ form.university_subject.label(class="form-control-label text-white  ml-sm-3") }}
                {{ form.university_subject(class="form-control mb-2 ml-sm-5 col-2") }}
                <div class="valid-feedback">مورد پذیرش</div>
                <div class="invalid-feedback">مورد پذیرش نیست</div>
                {{ form.degree.label(class="form-control-label text-white  ml-sm-3") }}
                {{ form.degree(class="form-control mb-2 ml-sm-5 col-2") }}
                <div class="valid-feedback">مورد پذیرش</div>
                <div class="invalid-feedback">مورد پذیرش نیست</div>
            </div>
            <hr/>
            {% if form.university.errors %}
                <ul class="form-group" align="right">
                {% for error in form.university.errors %}
                    <li class="alert alert-danger form-control">
                    {{ error }}
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
            {% if form.university_subject.errors %}
                <ul class="form-group" align="right">
                {% for error in form.university_subject.errors %}
                    <li class="alert alert-danger form-control">
                    {{ error }}
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
            {% if form.degree.errors %}
                <ul class="form-group" align="right">
                {% for error in form.degree.errors %}
                    <li class="alert alert-danger form-control">
                    {{ error }}
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
            <hr/>
            <p class='text-white mt-4' align="right">
            سوابق کاری
            </p>
            <hr/>
            <div class="form-inline">
                {{ form.work_reputations.label(class="form-control-label text-white") }}
                {{ form.work_reputations(class="form-control col-12") }}
                <div class="valid-feedback">مورد پذیرش</div>
                <div class="invalid-feedback">مورد پذیرش نیست</div>
            </div>
            <hr/>
            {% if form.work_reputations.errors %}
                <ul class="form-group" align="right">
                {% for error in form.work_reputations.errors %}
                    <li class="alert alert-danger form-control">
                    {{ error }}
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
            <hr/>
            <p class='text-white mt-4' align="right">
             مهارت ها
            </p>
            <hr/>
            <div class="form-check mb-4 form-align-right" align="right">
                {{ form.microcontroller.label(class="form-check-label text-white ml-1", align="right") }}
                {{ form.microcontroller(class="form-check-input mb-2 mr-1 ml-lg-5") }}
                {{ form.power.label(class="form-check-label text-white ml-1 mr-lg-5") }}
                {{ form.power(class="form-check-input mb-2 mr-1 ml-lg-5") }}
                {{ form.atmel_studio.label(class="form-check-label text-white ml-1 mr-lg-5", align="right") }}
                {{ form.atmel_studio(class="form-check-input mb-2 mr-1 ml-lg-5") }}
            </div>
            <div class="form-check" align="right">
                {{ form.altium_designer.label(class="form-check-label text-white ml-1", align="right") }}
                {{ form.altium_designer(class="form-check-input mb-2 mr-1 ml-lg-5") }}
                {{ form.arduino.label(class="form-check-label text-white ml-1 mr-lg-5") }}
                {{ form.arduino(class="form-check-input mb-2 mr-1 ml-lg-5") }}
                {{ form.code_vision.label(class="form-check-label text-white ml-1 mr-lg-5") }}
                {{ form.code_vision(class="form-check-input mb-2 mr-1 ml-lg-5") }}
                {{ form.proteus.label(class="form-check-label text-white ml-1 mr-lg-5") }}
                {{ form.proteus(class="form-check-input mb-2 mr-1") }}
            </div>
            <div class="form-inline mt-lg-4">
                {{ form.others.label(class="form-control-label text-white ml-3") }}
                {{ form.others(class="form-control col-12") }}
            </div>
            <hr/>
             <p class='text-white mt-4' align="right">
              حقوق پیشنهادی
            </p>
            <hr/>
            <div class="form-inline">
                {{ form.expected_salary.label(class="form-control-label text-white mb-3 mr-lg-5 ml-2") }}
                {{form.expected_salary(class="form-control mb-3") }}
                <div class="valid-feedback">مورد پذیرش</div>
                <div class="invalid-feedback">مورد پذیرش نیست</div>
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control btn btn-success", value="تائید") }}
            </div>
        </form>
        <script>
            // Add the following code if you want the name of the file appear on select
            $(".custom-file-input").on("change", function() {
                var fileName = $(this).val().split("\\").pop();
                $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
            });
        </script>
    </div>
</div>
{% endblock %}

forms/templates/electronics/index-el.html
{% extends 'base.html' %}

{% block title %}<title>Welcome</title>{% endblock %}

{% block content %}
{% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success allign-text-right" align="right">
                {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
<div class="card container mt-4 posts bg-dark">
    <div class="card-header">
        <h4 class="text-white text-allign-right" align="right">
        آگهی دعوت به همکاری
        </h4>
    </div>
    <div class="card-body">
        <p class="text-white" align="right">
        شرکت دانش بنیان فاپسکو مستقر در پارک علم و فناوری شیخ بهایی از واجدین شرایط جهت طراحی مدار های دیجیتال-الکترونیک-سوئیچینگ و طراحی سیستم های مکانیک دعوت به همکاری مینماید.
        ضمنا دارندگان کارشناسی ارشد و نخبه در تخصص های فوق الذکر به صورت امریه سربازی میتوانند از این فرصت استفاده نماید
        </p>
    </div>
    <div class="card-footer">
        <p class="text-white" align="right">
        در صورت تمایل برروی دکمه ثبت درخواست کلیک کنید
        <span align="left"><a href="{{ url_for('.create_request')}}" class="btn btn-success mr-3"> ثبت درخواست</a></span> 
        </p>
    </div>
</div>
{% endblock %}

forms/templates/electronics/resume-upload.html
{% extends 'base.html' %}

{% block title%}<title>job entry</title>{% endblock %}

{% block content %}
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class=" container alert alert-success allign-text-right mt-2" align="right">
            {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

<div class="card container mt-4 posts bg-dark">
    <div class="card-header">
        <h4 class="text-white text-allign-right" align="right">
        فرم درخواست همکاری
        </h4>
    </div>
    <div class="card-body" align="right">
        <form method="post" action="post" class="form-group" enctype="multipart/form-data">
            <input type="file" name="file" class="form-inline-input">
            <input type="submit" name="submit" value="آپلود" class="btn btn-success form-inline-input"> 
        </form>
        <script>
            // Add the following code if you want the name of the file appear on select
            $(".custom-file-input").on("change", function() {
                var fileName = $(this).val().split("\\").pop();
                $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
            });
        </script>
    </div>
    <div class="card-footer" align="right">
        <a class="btn btn-warning">
        رد کن
        </a>
    <div>
</div>
{% endblock %}